"""SPACE-DOPPLER harness tests (eval/space_doppler.py) — additive; nothing here touches the engine's
thresholds or bench-v2. They guard the two things the experiment's honesty rests on: the trajectory
is the shape the pre-registration declares, and the generator is not quietly broken (a generator bug
would make every trajectory finding void — hence criterion payload_correctness_on_control_cells).
"""
import os
import sys

import numpy as np

ROOT = os.path.join(os.path.dirname(__file__), '..')
sys.path.insert(0, os.path.join(ROOT, 'src'))
sys.path.insert(0, os.path.join(ROOT, 'eval'))

import space_doppler as sd                        # noqa: E402
from modem import load_iq, save_iq                # noqa: E402
from pipeline import CFO_MAX, analyze_iq          # noqa: E402

PEAK = 1.0 * CFO_MAX


def test_trajectory_shapes_match_the_pre_registration():
    n = 2048
    assert np.all(sd.trajectory('zero', PEAK, n) == 0.0)
    assert np.all(sd.trajectory('static', PEAK, n) == PEAK)

    lin = sd.trajectory('linear', PEAK, n)
    assert np.isclose(lin[0], -PEAK) and np.isclose(lin[-1], PEAK)
    assert np.allclose(np.diff(lin), lin[1] - lin[0])            # constant rate

    p = sd.trajectory('pass', PEAK, n)
    assert np.all(np.diff(p) > 0)                                # monotonic
    assert np.max(np.abs(p)) < PEAK                              # arctan is bounded inside the peak
    assert np.isclose(p[0], -p[-1])                              # antisymmetric about mid-pass
    # the S-curve's steepest section is steeper than the ramp spanning the same peaks
    assert np.max(np.diff(p)) > np.max(np.diff(lin))


def test_a_constant_trajectory_is_exactly_a_static_cfo():
    sig = np.exp(1j * np.linspace(0, 3, 256))
    mixed = sd.apply_trajectory(sig, sd.trajectory('static', PEAK, 256))
    assert np.allclose(mixed, sig * np.exp(2j * np.pi * PEAK * (np.arange(256) + 1)))


def test_severity_2_is_outside_the_engines_own_search_bound():
    """Pre-registered as an expected-refusal condition, and outside for a reason the engine itself
    declares (CFO_MAX) — not a number invented by the harness."""
    _, gt = sd._make('static', {'severity': 2.0, 'esn0': 12, 'length': 'short', 'rep': 0},
                     np.random.RandomState(1))
    assert gt['peak_shift_cyc_per_sample'] > CFO_MAX and gt['outside_search_bound']
    _, gt1 = sd._make('static', {'severity': 1.0, 'esn0': 12, 'length': 'short', 'rep': 0},
                      np.random.RandomState(1))
    assert not gt1['outside_search_bound']


def test_the_job_list_is_the_declared_grid_and_generation_is_seed_pure():
    js = sd.jobs()
    assert len(js) == 192 and len({i for i, _, _ in js}) == 192
    args = ('pass', {'severity': 0.5, 'esn0': 6, 'length': 'short', 'rep': 1})
    a, gta = sd._make(*args, np.random.RandomState(sd.SEED0 + 7))
    b, gtb = sd._make(*args, np.random.RandomState(sd.SEED0 + 7))
    assert np.array_equal(a, b) and gta == gtb
    c, _ = sd._make(*args, np.random.RandomState(sd.SEED0 + 8))
    assert not np.array_equal(a, c)


def test_a_control_vector_decodes_so_trajectory_findings_are_attributable():
    """Zero trajectory, 12 dB, long: the harness's own signal must be a signal the engine reads.
    If this fails, the experiment is measuring a generator bug, not a Doppler effect."""
    iq, gt = sd._make('zero', {'severity': 0.25, 'esn0': 12, 'length': 'long', 'rep': 0},
                      np.random.RandomState(sd.SEED0))
    outcome, note = sd._score(gt, analyze_iq(iq))
    assert outcome == 'DECODED_CORRECT', f'{outcome}: {note}'


def test_scoring_calls_a_wrong_payload_under_a_decode_claim_a_false_decode():
    gt = {'payload_bits': [0, 1, 0, 1] * 64, 'modulation': 'BPSK'}
    good = {'status': 'DECODED', 'code': 'conv_k7_continuous', 'modulation': 'BPSK',
            'payload_bits': gt['payload_bits']}
    assert sd._score(gt, good)[0] == 'DECODED_CORRECT'
    assert sd._score(gt, {**good, 'payload_bits': [1, 1, 1, 0] * 64})[0] == 'FALSE_DECODE'
    assert sd._score(gt, {**good, 'code': 'rs_255_223'})[0] == 'FALSE_DECODE'
    assert sd._score(gt, {**good, 'modulation': 'QPSK'})[0] == 'FALSE_DECODE'
    for status in ('SIGNAL_NO_CODE', 'UNKNOWN'):
        assert sd._score(gt, {**good, 'status': status})[0] == 'REFUSED'


def test_saved_bytes_are_the_bytes_the_manifest_hashes(tmp_path):
    """The determinism criterion compares regenerated bytes against the manifest, so the in-memory
    hash `verify` computes must be the hash of the file `generate` wrote."""
    import hashlib
    iq, _ = sd._make('linear', {'severity': 1.0, 'esn0': 9, 'length': 'short', 'rep': 0},
                     np.random.RandomState(sd.SEED0 + 3))
    path = str(tmp_path / 'x.iq')
    save_iq(path, iq)
    assert np.allclose(load_iq(path), iq, atol=1e-6)
    with open(path, 'rb') as f:
        on_disk = hashlib.sha256(f.read()).hexdigest()
    out = np.zeros(2 * len(iq), dtype=np.float32)
    out[0::2], out[1::2] = np.real(iq), np.imag(iq)
    assert hashlib.sha256(out.tobytes()).hexdigest() == on_disk
